### ISSUE TITLE
Could not find 'versionParser'

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [unimined/unimined#118]
A problem occurred evaluating root project 'Hudium'.
> Failed to apply plugin 'xyz.wagyourtail.unimined'.
   > Could not create an instance of type xyz.wagyourtail.unimined.UniminedExtensionImpl.
      > Could not create an instance of type xyz.wagyourtail.unimined.minecraft.MinecraftProviderImpl.
         > Could not find 'versionParser'
         
Repo with this issue: https://github.com/mrmasrozytlive/Hudium

**Comment by wagyourtail** [comment]
update unimined.
