### ISSUE TITLE
Mapping error only in github workflow

### ISSUE THREAD

**Issue by kurrycat2004** [unimined/unimined#25]
Build still works locally but fails with github workflow. Maybe an issue with the minecraft artifact file path on linux.
Still worked at this revision: https://github.com/unimined/unimined/tree/3e1887c629e48950db0a3b9f324274c9cd4a2526

Working github build from yesterday:
https://github.com/kurrycat2004/MPKMod_2/actions/runs/5224427002/jobs/9432608653
Same build now:
https://github.com/kurrycat2004/MPKMod_2/actions/runs/5227947604/jobs/9439958945

Using 1.0.0-SNAPSHOT

**Comment by wagyourtail** [comment]
I've committed many fixes in the past couple days. can you re-run it and let me know if it's still happening

**Comment by kurrycat2004** [comment]
Seems like this specific issue was fixed, at least the build is working now on github, thanks.
There are problems with the gradle run configurations though, but ill make a new issue for that
