### ISSUE TITLE
including a fabric 1.20 subproject breaks runClient task for fabric 1.19.4

### ISSUE THREAD

**Issue by kurrycat2004** [unimined/unimined#26]
Repo: https://github.com/kurrycat2004/MPKMod_2/tree/1.20

Probably always only works for the latest mc version, but i only tested it with 1.20 and 1.19.4.
Simply removing the include fabric-1.20 from the settings.gradle makes the runClient task for 1.19.4 work again.

Similar to the bug with forge for unimined 0.4.10 where it uses the same legacy_classpath.txt file for every forge subproject, which also causes only the latest run task to work. I didnt make an issue for this though because im not sure if it still exists for unimined 1.0.0 and i wasnt able to get forge running with unimined 1.0.0 and parchment mappings to test it

Edit: Just realized that its indeed similar, it uses `minecraft-1.20-fabric-merged+fixed-intermediary.jar` in `remapClasspath.txt` used for `-Dfabric.remapClasspathFile` instead of the 1.19.4 jar which probably means that the `remapClasspath.txt` simply gets overwritten because it configures the 1.20 subproject after the 1.19.4 one.

**Comment by wagyourtail** [comment]
good catch
