### ISSUE TITLE
Allow Babric to be used with side 'combined'

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#29]
That's the default way of working with it using babric-loom.

**Comment by thecatcore** [comment]
See this commit https://github.com/thecatcore/Mod-Remapping-API/commit/c076490181135da83afcbb0b39c0b649fe5362a2

**Comment by wagyourtail** [comment]
reprocessing worked, so I don't need https://github.com/thecatcore/Mod-Remapping-API/blob/275c59a6e110a84b374caa60bd1fa4af8c0302da/src/main/java/fr/catcore/modremapperapi/utils/MappingsUtils.java#L129 because it would break other things since I can't do this check properly.
