### ISSUE TITLE
Not all Minecraft assets are not extracted on Forge

### ISSUE THREAD

**Issue by ZeroMemes** [unimined/unimined#35]
Tested on 37513ff4e6c4ac9abaa95b5ea92d3932ceaf1576 using the included `/testing/1.20-Forge-Fabric` project.

<img src="https://github.com/unimined/unimined/assets/24485393/450de775-dd49-45b7-9f55-308452bb9160" width="400"/>

**Comment by ZeroMemes** [comment]
I have absolutely no idea what was wrong with my setup before, as it wouldn't launch due to failure to find assets on the classpath. Cleaning my project for probably the 10th time while working on other things has magically seemed to fix the issue.

I guess this "issue" doesn't actually have any real implications, and checking the jar produced by the Forge MDK confirms this, as it's the exact same.

<img src="https://github.com/unimined/unimined/assets/24485393/3c176704-dc8c-4cd6-9bc5-fa8779d796fe" width=400/>

**Comment by wagyourtail** [comment]
forge with fg3 splits assets into a client-extras jar... I put that in gradle as a file declaration so it'll be hidden at the top of your external dependencies
