### ISSUE TITLE
Cache version metadata

### ISSUE THREAD

**Issue by ZacSharp** [unimined/unimined#37]
I like working offline, but trying to build Baritone for 1.19.2 in offline mode results in this error, which does not go away after building with internet connection:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'baritone'.
> Offline mode is enabled, but version metadata is not available
```

**Comment by wagyourtail** [comment]
already fixed on latest
https://github.com/unimined/unimined/blob/35637a989b425d641ac0358cd31ed5f699be630f/src/minecraft/kotlin/xyz/wagyourtail/unimined/internal/minecraft/resolver/MinecraftDownloader.kt#L63-L90
