### ISSUE TITLE
Add task to transform code base from a mappings set to another

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#43]

**Comment by wagyourtail** [comment]
as in source remapping?

**Comment by thecatcore** [comment]
Yes, something similar to what Loom's migrateMappings task does.

**Comment by wagyourtail** [comment]
I'd like to use https://github.com/ReplayMod/remap but their license is incompatible (ignore readme, it's wrong)

**Comment by thecatcore** [comment]
Else we could probably use Fabric fork of Mercury

**Comment by wagyourtail** [comment]
completed as of https://github.com/unimined/unimined/commit/f6c402ec291245811ea581ea87418b5eb0b9e9b1
