### ISSUE TITLE
JarJar support

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#55]
Fabric/Quilt: JarInJar

Forge 1.15-1.16+: JarJar

Everything else: Shadow?

**Comment by wagyourtail** [comment]
what do you mean by this issue... fabric/quilt already have support for jij including stuff.

**Comment by thecatcore** [comment]
Somehow I can't find the code that handles it. I probably haven't looked hard enough.

**Comment by thecatcore** [comment]
Found it finally https://github.com/unimined/unimined/blob/main/src/minecraft/kotlin/xyz/wagyourtail/unimined/internal/minecraft/patch/fabric/FabricLikeMinecraftTransformer.kt#L60

**Comment by wagyourtail** [comment]
completed as of https://github.com/unimined/unimined/commit/7ef688ea37643636312aef5d92b09d6f63e348cc
