### ISSUE TITLE
Legacy forge coremods do not properly load in runClient

### ISSUE THREAD

**Issue by unix-supremacist** [unimined/unimined#59]
seems to be the true issue of #53 as well, but coremods do not load properly, which makes it really hard to develop cross loader mods using mixins, it can be worked around in some cases like in #53 but this is not ideal, and in the case of 1.7.10 with unimixins doing so just causes a NPE instead.

to reproduce, just clone this [example mod repo](https://github.com/LegacyModdingMC/examplemod) i'm working on, run the forge runClient and note that the mixins will never load in dev, if built and thrown in a production forge enviroment the mixins do load.

**Comment by wagyourtail** [comment]
```groovy
unimined.minecraft {
    ...
    
    runs.config("client") {
        args.addAll(["--tweakClass", "org.spongepowered.asm.launch.MixinTweaker"])
    }
}

**Comment by unix-supremacist** [comment]
this is said workaround i mentioned, that causes a NPE, even if it did work its not a proper replacement for unimined loading coremods properly in dev
