### ISSUE TITLE
Rift mixins not remapped

### ISSUE THREAD

**Issue by shizotoaster** [unimined/unimined#62]
Mixins in Rift projects seem to not be remapped. This leads to client crash after world creation or after some mods added to workspace (e.g. REI)

Crash log: https://pastes.dev/GBFkuO33uR

**Comment by dima-dencep** [comment]
Are you crazy? Svetlana Schizotoster cannot be ignored!!! @wagyourtail

**Comment by kakashi1464** [comment]
> Are you crazy? Svetlana Schizotoster cannot be ignored!!! @wagyourtail

![1099089174948216983](https://github.com/unimined/unimined/assets/126709049/11b9c31b-8c9d-4782-add7-1793c7edfa63)
