### ISSUE TITLE
Support Cleanroom for MC 1.12.2

### ISSUE THREAD

**Issue by Flamarine** [unimined/unimined#65]
Website: https://cleanroommc.com/
Basically Forge for 1.12.2 but 𝘸𝘢𝘩𝘩 𝘵𝘦𝘤𝘩𝘯𝘰𝘭𝘰𝘨𝘺

**Comment by wagyourtail** [comment]
https://github.com/unimined/unimined/commit/a83d9eefcbf66c5cf3eaa288d75c057200634118
