### ISSUE TITLE
[Fabric] Support merged intermediary format, officially supported from Loom 1.6 onwards

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#66]
See https://github.com/FabricMC/fabric-loom/pull/1026.
Babric used the following headers for merged intermediary:
`intermediary`, `glue`, `server`, `client`.
Loom 1.6 will introduce official support for:
`intermediary`, `clientOfficial`, `serverOfficial`

**Comment by wagyourtail** [comment]
yeah, following this on ornithe, this is planned
