### ISSUE TITLE
Add support for really old AT format.

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#96]
Really old versions of forge use a slightly different format for AT where instead of a space between the class name and the member there is a point.

Example with Forge 1.3.2 fml_at:
![image](https://github.com/user-attachments/assets/64aa5410-3d24-4f3c-bbf1-20caf83adbd1)

**Comment by wagyourtail** [comment]
the support should be there...
https://github.com/unimined/unimined/blob/5561b47f781241122796b6a3eb0cbe511339109f/src/mapping/kotlin/xyz/wagyourtail/unimined/internal/mapping/at/AccessTransformerApplier.kt#L97

and in the 1.4 branch
https://github.com/unimined/unimined/blob/c1c3081d94295b76ea693f5f66f85411fac06c0d/src/mapping/kotlin/xyz/wagyourtail/unimined/internal/mapping/at/AccessTransformerApplier.kt#L64
